// Generate NixOS configuration.nix

import type { AppData } from './data';

export interface NixConfigOptions {
    packages: { app: AppData; pkg: string }[];
    includeSystem?: boolean;
    includeNetwork?: boolean;
    includeServices?: boolean;
}

export function generateNixConfiguration(options: NixConfigOptions): string {
    const { packages, includeSystem = true, includeNetwork = true, includeServices = true } = options;

    const pkgList = packages.map(({ pkg }) => `    pkgs.${pkg}`).join('\n');

    return `# NixOS Configuration
# Generated by Linux App Installer
# ${new Date().toISOString()}

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
  ];

${includeSystem ? generateSystemConfig() : ''}

${includeNetwork ? generateNetworkConfig() : ''}

  # System packages
  environment.systemPackages = with pkgs; [
${pkgList}
  ];

${includeServices ? generateServicesConfig(packages) : ''}

  # This value determines the NixOS release.
  system.stateVersion = "24.05"; # Did you read the comment?
}
`;
}

function generateSystemConfig(): string {
    return `  # Boot loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Time zone
  time.timeZone = "UTC";

  # Internationalisation
  i18n.defaultLocale = "en_US.UTF-8";

  # Console keymap
  console.keyMap = "us";
`;
}

function generateNetworkConfig(): string {
    return `  # Networking
  networking.networkmanager.enable = true;
  # networking.hostName = "nixos";
`;
}

function generateServicesConfig(packages: { app: AppData; pkg: string }[]): string {
    const hasDocker = packages.some(p => p.pkg === 'docker');
    const hasOpenSSH = packages.some(p => p.pkg === 'openssh');

    let config = '';

    if (hasDocker) {
        config += `  # Docker
  virtualisation.docker.enable = true;
  # users.users.YOUR_USER.extraGroups = [ "docker" ];

`;
    }

    if (hasOpenSSH) {
        config += `  # OpenSSH daemon
  services.openssh.enable = true;
  # services.openssh.settings.PermitRootLogin = "no";

`;
    }

    return config;
}

export function downloadNixConfig(config: string, filename = 'configuration.nix') {
    const blob = new Blob([config], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
